#!/usr/bin/env python3
"""Generate supabase/seed.sql from data/plots.geojson.

The seed is the ONE-TIME initial load for the Supabase `plots` table (after that,
the database is the source of truth and the admin edits rows directly — the
CW.xlsx workbook and this seed are retired). Re-runnable: uses INSERT ... ON
CONFLICT DO UPDATE, so loading it twice just refreshes the rows.

Only public/record fields are written. `internal_notes` is left NULL here; the
private workbook notes are never committed and can be loaded separately by the
admin if desired (see docs/DEPLOY.md).

Usage: python3 scripts/export_seed.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLOTS = ROOT / "data/plots.geojson"
OUT = ROOT / "supabase/seed.sql"


def sql_str(v) -> str:
    """Quote a value for SQL, doubling single quotes; None -> NULL."""
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def main() -> None:
    fc = json.loads(PLOTS.read_text())
    rows = []
    for f in fc["features"]:
        p = f["properties"]
        person = p.get("person") or {}
        rows.append((
            p["id"],
            p["lot"],
            p["space"],
            p["status"],
            p.get("color"),
            p.get("owner"),
            person.get("name"),
            person.get("burial"),
        ))
    rows.sort(key=lambda r: (r[1], r[2]))  # by lot, then space

    lines = [
        "-- Cook-Walden IABA map — initial data load (generated by "
        "scripts/export_seed.py)",
        "-- Run AFTER supabase/schema.sql. Safe to re-run (upserts by id).",
        "",
        "insert into public.plots",
        "  (id, lot, space, status, color, owner, person_name, person_burial)",
        "values",
    ]
    values = []
    for id_, lot, space, status, color, owner, name, burial in rows:
        values.append(
            f"  ({sql_str(id_)}, {lot}, {sql_str(space)}, {sql_str(status)}, "
            f"{sql_str(color)}, {sql_str(owner)}, {sql_str(name)}, "
            f"{('DATE ' + sql_str(burial)) if burial else 'NULL'})"
        )
    lines.append(",\n".join(values))
    lines.append("on conflict (id) do update set")
    lines.append("  lot = excluded.lot,")
    lines.append("  space = excluded.space,")
    lines.append("  status = excluded.status,")
    lines.append("  color = excluded.color,")
    lines.append("  owner = excluded.owner,")
    lines.append("  person_name = excluded.person_name,")
    lines.append("  person_burial = excluded.person_burial;")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} — {len(rows)} plots")
    print(f"  with owner:  {sum(1 for r in rows if r[5])}")
    print(f"  with person: {sum(1 for r in rows if r[6])}")


if __name__ == "__main__":
    main()
